### PR TITLE
Update readme with an example of repo structure

### PR DESCRIPTION
**Pull request by JuraJuki**
• Adds example  of app structure to readme
• Adds most common directories to the template
• Moves App files to root/ directory

### CODE REVIEW

**Comment by ShockwaVee** [comment]
@JuraJuki Does it make sense to list out all the scripts you can run like npm start (or the equivalent in yarn) and others?

**Comment by renatoruk** [comment]
Hey, @JuraJuki, some cool ideas in here about structure.

But, wouldn't it make sense to actually create these directories already in the repo so when you use the template, they're already there? You might only explain them in the docs

**Comment by JuraJuki** [comment]
> Hey, @JuraJuki, some cool ideas in here about structure.
> 
> But, wouldn't it make sense to actually create these directories already in the repo so when you use the template, they're already there? You might only explain them in the docs

It would make sense for some of the most common directories, sure. I wouldn't go about adding the ones which are less common because most projects are going to be of a lesser size.

**Comment by JuraJuki** [comment]
@ShockwaVee @renatoruk Updated the description and readme. Added most common directories and moved App files to /root/

**Comment by renatoruk** [comment]
@JuraJuki You can use gitkeep for preserving dir structure https://stackoverflow.com/a/7230006/5278557

**Pull request merged**
